<a href="https://colab.research.google.com/github/svafaeva93/deep-learning-challenge/blob/main/AlphabetSoup_Optimization1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Preprocessing

In [1]:
# Import our dependencies
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import ModelCheckpoint
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns = ["EIN", "NAME"])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [3]:
# Determine the number of unique values in each column.
unique_values_count = application_df.nunique()
print(unique_values_count)

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
application_type_counts = application_df["APPLICATION_TYPE"].value_counts()
application_type_counts

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(application_type_counts[application_type_counts < 500].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
classification_type_counts = application_df['CLASSIFICATION'].value_counts()
print(classification_type_counts)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classification_counts_gt_1 = classification_type_counts[classification_type_counts > 1]
print(classification_counts_gt_1)

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = list (classification_type_counts[classification_type_counts<1000].index)
classifications_to_replace

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
C2000     6074
C1200     4837
Other     2261
C3000     1918
C2100     1883
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
numeric_df = pd.get_dummies(application_df)
numeric_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,1,108590,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,1,0
2,1,5000,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,1,0
3,1,6692,1,0,0,0,1,0,0,0,...,0,1,0,0,0,0,0,0,1,0
4,1,142590,1,0,0,0,1,0,0,0,...,0,0,1,0,0,0,0,0,1,0

In [10]:
# Split our preprocessed data into our features and target arrays
y = numeric_df["IS_SUCCESSFUL"].values.reshape(-1,1)
X = numeric_df.drop(["IS_SUCCESSFUL"],1)

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X,y, random_state = 42)

<ipython-input-10-91e3c833d42b>:3: FutureWarning: In a future version of pandas all arguments of DataFrame.drop except for the argument 'labels' will be keyword-only.
  X = numeric_df.drop(["IS_SUCCESSFUL"],1)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train.values[0])

hidden_nodes_layer1 = 50
hidden_nodes_layer2 = 20
hidden_nodes_layer3 = 5


nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer2, activation="relu"))

# Third hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer3, activation="tanh"))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 50)                2200

 dense_1 (Dense)             (None, 20)                1020

 dense_2 (Dense)             (None, 5)                 105

 dense_3 (Dense)             (None, 1)                 6

=================================================================
Total params: 3,331
Trainable params: 3,331
Non-trainable params: 0
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [15]:
# Create directory if it does not exist
if not os.path.exists('/Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2'):
    os.makedirs('/Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2')

# Define the checkpoint path
checkpoint_path = "/Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.{epoch:02d}.hdf5"

# Create the checkpoint callback
checkpoint_callback = ModelCheckpoint(
    filepath=checkpoint_path,
    verbose=1,
    save_weights_only=True,
    save_freq='epoch',
    period = 5
)

WARNING:tensorflow:`period` argument is deprecated. Please use `save_freq` to specify the frequency in number of batches seen.

In [16]:
# Train the model
nn.fit(X_train_scaled, y_train, epochs=100, callbacks=[checkpoint_callback])

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5732 - accuracy: 0.7188
Epoch 2/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5551 - accuracy: 0.7296
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5524 - accuracy: 0.7290
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5513 - accuracy: 0.7307
Epoch 5/100
783/804 [============================>.] - ETA: 0s - loss: 0.5496 - accuracy: 0.7296
Epoch 5: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.05.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5489 - accuracy: 0.7298
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5484 - accuracy: 0.7315
Epoch 7/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5476 - accuracy: 0.7315
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5471 - accuracy: 0.7327
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5464 - accuracy: 0.7327
Epoch 10/100
788/804 [============================>.] - ETA: 0s - loss: 0.5453 - accuracy: 0.7320
Epoch 10: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.10.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5455 - accuracy: 0.7319
Epoch 11/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5447 - accuracy: 0.7343
Epoch 12/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5444 - accuracy: 0.7337
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5438 - accuracy: 0.7333
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5441 - accuracy: 0.7343
Epoch 15/100
803/804 [============================>.] - ETA: 0s - loss: 0.5430 - accuracy: 0.7346
Epoch 15: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.15.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5428 - accuracy: 0.7346
Epoch 16/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5426 - accuracy: 0.7358
Epoch 17/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5432 - accuracy: 0.7344
Epoch 18/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5422 - accuracy: 0.7351
Epoch 19/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5426 - accuracy: 0.7341
Epoch 20/100
797/804 [============================>.] - ETA: 0s - loss: 0.5426 - accuracy: 0.7351
Epoch 20: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.20.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5421 - accuracy: 0.7352
Epoch 21/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5422 - accuracy: 0.7343
Epoch 22/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5416 - accuracy: 0.7352
Epoch 23/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5416 - accuracy: 0.7346
Epoch 24/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5412 - accuracy: 0.7370
Epoch 25/100
801/804 [============================>.] - ETA: 0s - loss: 0.5407 - accuracy: 0.7358
Epoch 25: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.25.hdf5
804/804 [==============================] - 4s 4ms/step - loss: 0.5412 - accuracy: 0.7355
Epoch 26/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5411 - accuracy: 0.7353
Epoch 27/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7372
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5401 - accuracy: 0.7368
Epoch 29/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5402 - accuracy: 0.7365
Epoch 30/100
791/804 [============================>.] - ETA: 0s - loss: 0.5396 - accuracy: 0.7370
Epoch 30: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.30.hdf5
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7367
Epoch 31/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5405 - accuracy: 0.7362
Epoch 32/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5403 - accuracy: 0.7366
Epoch 33/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5401 - accuracy: 0.7382
Epoch 34/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5397 - accuracy: 0.7374
Epoch 35/100
782/804 [============================>.] - ETA: 0s - loss: 0.5398 - accuracy: 0.7369
Epoch 35: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.35.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7375
Epoch 36/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5396 - accuracy: 0.7365
Epoch 37/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7369
Epoch 38/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5394 - accuracy: 0.7372
Epoch 39/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5391 - accuracy: 0.7376
Epoch 40/100
796/804 [============================>.] - ETA: 0s - loss: 0.5384 - accuracy: 0.7384
Epoch 40: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.40.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5390 - accuracy: 0.7379
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5393 - accuracy: 0.7366
Epoch 42/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5387 - accuracy: 0.7372
Epoch 43/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5385 - accuracy: 0.7367
Epoch 44/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5388 - accuracy: 0.7368
Epoch 45/100
802/804 [============================>.] - ETA: 0s - loss: 0.5388 - accuracy: 0.7375
Epoch 45: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.45.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5388 - accuracy: 0.7374
Epoch 46/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5386 - accuracy: 0.7363
Epoch 47/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5386 - accuracy: 0.7374
Epoch 48/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5381 - accuracy: 0.7385
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5386 - accuracy: 0.7363
Epoch 50/100
783/804 [============================>.] - ETA: 0s - loss: 0.5384 - accuracy: 0.7383
Epoch 50: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.50.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5385 - accuracy: 0.7383
Epoch 51/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5380 - accuracy: 0.7382
Epoch 52/100
804/804 [==============================] - 4s 5ms/step - loss: 0.5383 - accuracy: 0.7377
Epoch 53/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5382 - accuracy: 0.7371
Epoch 54/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5380 - accuracy: 0.7378
Epoch 55/100
798/804 [============================>.] - ETA: 0s - loss: 0.5382 - accuracy: 0.7377
Epoch 55: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.55.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5386 - accuracy: 0.7376
Epoch 56/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5382 - accuracy: 0.7380
Epoch 57/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7383
Epoch 58/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7386
Epoch 59/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7370
Epoch 60/100
804/804 [==============================] - ETA: 0s - loss: 0.5376 - accuracy: 0.7380
Epoch 60: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.60.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7380
Epoch 61/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7380
Epoch 62/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5377 - accuracy: 0.7383
Epoch 63/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7380
Epoch 64/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5374 - accuracy: 0.7381
Epoch 65/100
786/804 [============================>.] - ETA: 0s - loss: 0.5379 - accuracy: 0.7372
Epoch 65: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.65.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7376
Epoch 66/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5376 - accuracy: 0.7374
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5375 - accuracy: 0.7388
Epoch 68/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7381
Epoch 69/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7386
Epoch 70/100
796/804 [============================>.] - ETA: 0s - loss: 0.5370 - accuracy: 0.7389
Epoch 70: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.70.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5373 - accuracy: 0.7385
Epoch 71/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5371 - accuracy: 0.7388
Epoch 72/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5372 - accuracy: 0.7385
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5371 - accuracy: 0.7379
Epoch 74/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5372 - accuracy: 0.7390
Epoch 75/100
790/804 [============================>.] - ETA: 0s - loss: 0.5365 - accuracy: 0.7384
Epoch 75: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.75.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5367 - accuracy: 0.7385
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7387
Epoch 77/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5370 - accuracy: 0.7381
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7385
Epoch 79/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5367 - accuracy: 0.7389
Epoch 80/100
792/804 [============================>.] - ETA: 0s - loss: 0.5367 - accuracy: 0.7384
Epoch 80: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.80.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7388
Epoch 81/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7396
Epoch 82/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7391
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5360 - accuracy: 0.7398
Epoch 84/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5370 - accuracy: 0.7397
Epoch 85/100
791/804 [============================>.] - ETA: 0s - loss: 0.5362 - accuracy: 0.7392
Epoch 85: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.85.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7390
Epoch 86/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5366 - accuracy: 0.7385
Epoch 87/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5364 - accuracy: 0.7387
Epoch 88/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7389
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5361 - accuracy: 0.7393
Epoch 90/100
792/804 [============================>.] - ETA: 0s - loss: 0.5362 - accuracy: 0.7378
Epoch 90: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.90.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7376
Epoch 91/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5360 - accuracy: 0.7383
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5365 - accuracy: 0.7384
Epoch 93/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5368 - accuracy: 0.7386
Epoch 94/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5362 - accuracy: 0.7388
Epoch 95/100
776/804 [===========================>..] - ETA: 0s - loss: 0.5351 - accuracy: 0.7398
Epoch 95: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.95.hdf5
804/804 [==============================] - 1s 2ms/step - loss: 0.5364 - accuracy: 0.7387
Epoch 96/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5361 - accuracy: 0.7386
Epoch 97/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5365 - accuracy: 0.7392
Epoch 98/100
804/804 [==============================] - 1s 2ms/step - loss: 0.5360 - accuracy: 0.7403
Epoch 99/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5357 - accuracy: 0.7391
Epoch 100/100
784/804 [============================>.] - ETA: 0s - loss: 0.5360 - accuracy: 0.7397
Epoch 100: saving model to /Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/weights.100.hdf5
804/804 [==============================] - 2s 2ms/step - loss: 0.5362 - accuracy: 0.7392

In [17]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5581 - accuracy: 0.7263 - 486ms/epoch - 2ms/step
Loss: 0.5581293106079102, Accuracy: 0.7262973785400391

In [18]:
# Export our model to HDF5 file
nn.save('/Users/shakhnoza/Documents/GitHub/deep-learning-challenge/models/model_2/AlphabetSoupCharity_Optimization1.h5')